walkmod-gradle-plugin
=====================
Raquel Pau <raquelpau@gmail.com>


This is a walkmod plugin to load the classpath of a gradle project.

== Usage

. Add the https://github.com/rpau/walkmod-gradle-plugin[walkmod-gradle-plugin] into your `walkmod.xml` as a plugin. 
This plugin will interpret your classpath accoding your `build.gradle` and will compile your code.

. Add other Walkmod plugins and your transformations that depend on having the classpath resolved. 

. Add the transformations `walkmod:commons:unused-declarations-cleaner` into your  `walkmod.xml` and 
set your refactoring configurations.

```XML
<!DOCTYPE walkmod PUBLIC "-//WALKMOD//DTD"  "http://www.walkmod.com/dtd/walkmod-1.0.dtd" >
<walkmod>
  <plugins>
    <plugin groupId="org.walkmod" artifactId="walkmod-gradle-plugin" version="[1.0,)" />
  </plugins>
  <conf-providers>
    <conf-provider type="walkmod:commons:maven"></conf-provider>
  </conf-providers>
  <chain name="main-chain">	
    <transformation type="...."/>
  </chain>	
</walkmod>
```

You can apply walkmod-imports-cleaner-plugin via walkmod. 

  $ walkmod apply

Or, you can also check which would be the modified classes typing:

  $ walkmod check

== Contributing

If you want to hack on this, fork it, improve it and send me a pull request.

To get started using it, just clone it and call mvn install. 


