walkmod-gradle-plugin
=====================
Raquel Pau <raquelpau@gmail.com>

image:https://travis-ci.org/rpau/walkmod-gradle-plugin.svg?branch=master["Build Status", link="https://travis-ci.org/rpau/walkmod-gradle-plugin"]

This is a walkmod plugin to load the classpath of a gradle project.

== Usage

=== Walkmod >= 2.2.3

You don't need to do extra work to execute your plugins. However, you can force to execute it before executing any 
code transformation with the following command.
----
walkmod add-provider gradle
----

If you have multiple gradle flavors, you need to specify which flavor is the valid one to use as the classpath of the project as follows:

----
walkmod add-provider -Dflavor="MYFLAVOR" gradle
----

In case of using local libraries (that do not belong to the maven local repo), you should specify them manually as follows:
----
walkmod add-provider -DlocalLibs="[\"libDir/\", \"lib2.jar\"]" gradle
----
=== Older versions
. Add the https://github.com/rpau/walkmod-gradle-plugin[walkmod-gradle-plugin] into your `walkmod.xml` as a configuration provider. 
This component will interpret your classpath accoding your `build.gradle` and will compile your code.

. Add other Walkmod plugins and your transformations that depend on having the classpath resolved. 

```XML
<!DOCTYPE walkmod PUBLIC "-//WALKMOD//DTD"  "http://www.walkmod.com/dtd/walkmod-1.1.dtd" >
<walkmod>
  <conf-providers>
    <conf-provider type="gradle"></conf-provider>
  </conf-providers>
  <chain name="main-chain">	
    <transformation type="...."/>
  </chain>	
</walkmod>
```

You can apply walkmod-gradle-plugin via walkmod. 

  $ walkmod apply

Or, you can also check which would be the modified classes typing:

  $ walkmod check

== Contributing

If you want to hack on this, fork it, improve it and send me a pull request.

To get started using it, just clone it and call mvn install. 


